<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = array(
            array(
                'name' => 'Super Bowl Halftime',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '123 Main Street',
                'city' => 'City 1',
                'country' => 'Country 1',
                'zip_code' => '12345',
                'latitude' => '12.34445',
                'longitude' => '67.83290',
                'phone' => '123-456-7890',
                'email' => 'info@eventcompany1.com',
                'website' => 'https://www.eventcompany1.com',
                'check_in' => '02:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-07-25',
                'price' => 50000
            ),
            array(
                'name' => 'Solstice Celebration',
                'description' => 'Offering experts in event management, seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '456 Elm Street',
                'city' => 'City 2',
                'country' => 'Country 2',
                'zip_code' => '67890',
                'latitude' => '34.23567',
                'longitude' => '12.34545',
                'phone' => '234-567-8901',
                'email' => 'info@eventcompany2.com',
                'website' => 'https://www.eventcompany2.com',
                'check_in' => '02:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-08-25',
                'price' => 75000
            ),
            array(
                'name' => 'NewYork Marathon',
                'description' => 'Seamless planning and execution for memorable corporate and social gatherings, offering experts in event management.',
                'address' => '789 Oak Avenue',
                'city' => 'City 3',
                'country' => 'Country 3',
                'zip_code' => '54321',
                'latitude' => '98.75565',
                'longitude' => '43.21230',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany3.com',
                'website' => 'https://www.eventcompany3.com',
                'check_in' => '03:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-05-25',
                'price' => 60000
            ),
            array(
                'name' => 'Coachella Festival',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '987 Maple Lane',
                'city' => 'City 4',
                'country' => 'Country 4',
                'zip_code' => '09876',
                'latitude' => '76.54333',
                'longitude' => '32.10119',
                'phone' => '456-789-0123',
                'email' => 'info@eventcompany4.com',
                'website' => 'https://www.eventcompany4.com',
                'check_in' => '02:00 PM',
                'check_out' => '11:00 PM',
                'date' => '2023-05-25',
                'price' => 80000
            ),
            array(
                'name' => 'Academy Awards',
                'description' => 'Offering experts in event management, seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '321 Pine Road',
                'city' => 'City 5',
                'country' => 'Country 5',
                'zip_code' => '56789',
                'latitude' => '54.32331',
                'longitude' => '98.75565',
                'phone' => '567-890-1234',
                'email' => 'info@eventcompany5.com',
                'website' => 'https://www.eventcompany5.com',
                'check_in' => '02:00 PM',
                'check_out' => '12:00 PM',
                'date' => '2023-07-15',
                'price' => 65000
            ),
            array(
                'name' => 'Tour De France',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '543 Cedar Avenue',
                'city' => 'City 6',
                'country' => 'Country 6',
                'zip_code' => '76543',
                'latitude' => '21.34455',
                'longitude' => '87.90441',
                'phone' => '678-901-2345',
                'email' => 'info@eventcompany6.com',
                'website' => 'https://www.eventcompany6.com',
                'check_in' => '04:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-08-25',
                'price' => 90000
            ),
            array(
                'name' => 'Christmas Lighting',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '876 Oak Street',
                'city' => 'City 7',
                'country' => 'Country 7',
                'zip_code' => '34567',
                'latitude' => '65.43332',
                'longitude' => '09.83376',
                'phone' => '789-012-3456',
                'email' => 'info@eventcompany7.com',
                'website' => 'https://www.eventcompany7.com',
                'check_in' => '01:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-09-05',
                'price' => 70000
            ),
            array(
                'name' => 'World Series Finale',
                'description' => 'Offering experts in event management, seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '234 Elm Avenue',
                'city' => 'City 8',
                'country' => 'Country 8',
                'zip_code' => '90123',
                'latitude' => '43.21330',
                'longitude' => '65.43332',
                'phone' => '890-123-4567',
                'email' => 'info@eventcompany8.com',
                'website' => 'https://www.eventcompany8.com',
                'check_in' => '06:00 PM',
                'check_out' => '11:00 PM',
                'date' => '2023-04-25',
                'price' => 55000
            ),
            array(
                'name' => 'Art Basel Exhibition',
                'description' => 'Offering experts in event management, seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '567 Pine Street',
                'city' => 'City 9',
                'country' => 'Country 9',
                'zip_code' => '45678',
                'latitude' => '32.10119',
                'longitude' => '54.33321',
                'phone' => '012-345-6789',
                'email' => 'info@eventcompany9.com',
                'website' => 'https://www.eventcompany9.com',
                'check_in' => '02:00 PM',
                'check_out' => '11:00 PM',
                'date' => '2023-07-05',
                'price' => 75000
            ),
            array(
                'name' => 'Burning Man Festival',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 10',
                'country' => 'Country 10',
                'zip_code' => '23456',
                'latitude' => '87.94301',
                'longitude' => '21.34335',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany10.com',
                'website' => 'https://www.eventcompany10.com',
                'check_in' => '01:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-06-25',
                'price' => 86000
            ),
            array(
                'name' => 'Mardi Gras parade',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 11',
                'country' => 'Country 11',
                'zip_code' => '23416',
                'latitude' => '87.90111',
                'longitude' => '21.31145',
                'phone' => '345-618-9012',
                'email' => 'info@eventcompany11.com',
                'website' => 'https://www.eventcompany11.com',
                'check_in' => '01:00 PM',
                'check_out' => '09:00 PM',
                'date' => '2023-07-11',
                'price' => 78000
            ),
            array(
                'name' => 'Oktoberfest Festival',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 12',
                'country' => 'Country 12',
                'zip_code' => '23256',
                'latitude' => '87.90221',
                'longitude' => '21.32245',
                'phone' => '345-678-9212',
                'email' => 'info@eventcompany12.com',
                'website' => 'https://www.eventcompany12.com',
                'check_in' => '02:00 PM',
                'check_out' => '08:00 PM',
                'date' => '2023-10-22',
                'price' => 92000
            ),
            array(
                'name' => 'Rio Carnival Parade',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 13',
                'country' => 'Country 13',
                'zip_code' => '22456',
                'latitude' => '87.90331',
                'longitude' => '21.34335',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany13.com',
                'website' => 'https://www.eventcompany13.com',
                'check_in' => '07:00 PM',
                'check_out' => '12:00 PM',
                'date' => '2023-11-23',
                'price' => 83000
            ),
            array(
                'name' => 'London Fashion Week',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 14',
                'country' => 'Country 14',
                'zip_code' => '23454',
                'latitude' => '87.90441',
                'longitude' => '21.34543',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany14.com',
                'website' => 'https://www.eventcompany14.com',
                'check_in' => '02:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-05-25',
                'price' => 85000
            ),
            array(
                'name' => 'Comic-Con Convention',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 15',
                'country' => 'Country 15',
                'zip_code' => '24556',
                'latitude' => '87.95015',
                'longitude' => '21.34555',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany15.com',
                'website' => 'https://www.eventcompany15.com',
                'check_in' => '03:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-07-25',
                'price' => 80000
            ),
            array(
                'name' => 'Times Square Ball',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 16',
                'country' => 'Country 16',
                'zip_code' => '23456',
                'latitude' => '87.96061',
                'longitude' => '21.36645',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany16.com',
                'website' => 'https://www.eventcompany16.com',
                'check_in' => '02:00 PM',
                'check_out' => '11:00 PM',
                'date' => '2023-06-25',
                'price' => 80000
            ),
            array(
                'name' => 'Cannes Film Festival',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 17',
                'country' => 'Country 17',
                'zip_code' => '23456',
                'latitude' => '87.97701',
                'longitude' => '21.37745',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany17.com',
                'website' => 'https://www.eventcompany17.com',
                'check_in' => '04:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-09-25',
                'price' => 90000
            ),
            array(
                'name' => 'Kentucky Derby Race',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 18',
                'country' => 'Country 18',
                'zip_code' => '23456',
                'latitude' => '87.98801',
                'longitude' => '21.34885',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany18.com',
                'website' => 'https://www.eventcompany18.com',
                'check_in' => '02:00 PM',
                'check_out' => '06:00 PM',
                'date' => '2023-04-25',
                'price' => 83000
            ),
            array(
                'name' => 'Sydney Opera House',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 19',
                'country' => 'Country 19',
                'zip_code' => '77456',
                'latitude' => '87.90671',
                'longitude' => '23.34665',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany19.com',
                'website' => 'https://www.eventcompany19.com',
                'check_in' => '02:00 PM',
                'check_out' => '06:00 PM',
                'date' => '2023-02-25',
                'price' => 88000
            ),
            array(
                'name' => 'Running of Bulls',
                'description' => 'Experts in event management, offering seamless planning and execution for memorable corporate and social gatherings.',
                'address' => '789 Oak Road',
                'city' => 'City 20',
                'country' => 'Country 20',
                'zip_code' => '23356',
                'latitude' => '87.22021',
                'longitude' => '21.38945',
                'phone' => '345-678-9012',
                'email' => 'info@eventcompany20.com',
                'website' => 'https://www.eventcompany20.com',
                'check_in' => '02:00 PM',
                'check_out' => '10:00 PM',
                'date' => '2023-04-25',
                'price' => 85000
            )
        );

        foreach ($events as $event){
            // generate  random number between 1 & 10 and add as the
            // category_id to the event array
            $event['category_id'] = rand(1, 10);
            \App\Models\Event::create($event);
        }
    }
}
